server:
  port: 8080 # 启动端口
  address: 0.0.0.0 # 允许外部访问
  servlet:
    context-path: / # 根路径

spring:
  application:
    name: satellite-service

  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

  web:
    resources:
      static-locations: classpath:/static/ # 静态资源访问路径

    cors:
      mappings:
        - path: /**
          allowed-origins: "*"
          allowed-methods: "*"
          allowed-headers: "*"

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

logging:
  level:
    root: info
    com.iscas: debug # 你的项目包名（修改为你自己的）
  file:
    name: logs/app.log
